import type { TrendingAnalysisResult } from './types/index.js'
import { writeFileSync } from 'node:fs'

import { generateEmail } from './src/email/emailGenerator.js'

const mockAnalysis: TrendingAnalysisResult = {
  date: '2026-01-29',
  theme: 'AI 工具革命 · 智能体开发浪潮',
  topProject: {
    name: 'anthropics/claude-agent-sdk',
    summary: 'Anthropic 官方 Claude Agent SDK，提供完整的工具调用和执行能力',
    techStack: ['TypeScript', 'Node.js', 'Claude API'],
    features: [
      '内置 Web Search 集成',
      '自动 Tool Use 执行循环',
      'MCP Server 支持',
      '并行工具调用优化',
    ],
    trendingReason: 'AI Agent 开发成为今年最热趋势，开发者急需高效的工具调用框架',
    recommendationScore: 9,
    recommendationReason: '官方出品，稳定可靠，提供完整的 Agent 开发能力',
    isNewProject: false,
    starsChange: 1234,
    popularityTrend: 'rising',
    highlightLevel: 'top',
    category: 'AI 工具',
  },
  techTrends: ['AI Agents 智能体', 'RAG 增强检索', 'Web Components', 'TypeScript', 'Rust'],
  newProjectCount: 3,
  projects: [
    {
      name: 'anthropics/claude-agent-sdk',
      summary: 'Anthropic 官方 Claude Agent SDK，提供完整的工具调用和执行能力',
      techStack: ['TypeScript', 'Node.js', 'Claude API'],
      features: [
        '内置 Web Search 集成',
        '自动 Tool Use 执行循环',
        'MCP Server 支持',
        '并行工具调用优化',
      ],
      trendingReason: 'AI Agent 开发成为今年最热趋势，开发者急需高效的工具调用框架',
      recommendationScore: 9,
      recommendationReason: '官方出品，稳定可靠，提供完整的 Agent 开发能力',
      isNewProject: false,
      starsChange: 1234,
      popularityTrend: 'rising',
      highlightLevel: 'top',
      category: 'AI 工具',
    },
    {
      name: 'vercel/ai-sdk',
      summary: 'Vercel 推出的 AI 模型统一开发框架，支持多家大模型提供商',
      techStack: ['TypeScript', 'React', 'Next.js'],
      features: [
        '统一的 AI 模型接口',
        '支持多家提供商',
        '流式响应优化',
        'React Hooks 集成',
      ],
      trendingReason: '开发者需要统一的 AI 模型调用接口，简化多模型集成',
      recommendationScore: 8,
      recommendationReason: 'Vercel 生态集成完善，开发者接受度高',
      isNewProject: false,
      starsChange: 890,
      popularityTrend: 'stable',
      highlightLevel: 'recommended',
      category: 'AI 框架',
    },
    {
      name: 'openai/openai-node',
      summary: 'OpenAI 官方 Node.js SDK，最新版本增加了多模态和流式支持',
      techStack: ['TypeScript', 'Node.js'],
      features: [
        '多模态 API 支持',
        '流式响应',
        '函数调用优化',
        'TypeScript 原生支持',
      ],
      trendingReason: 'OpenAI 更新 SDK，增加了新的 API 功能和性能优化',
      recommendationScore: 8,
      recommendationReason: '官方 SDK，更新及时，文档完善',
      isNewProject: false,
      starsChange: 567,
      popularityTrend: 'rising',
      highlightLevel: 'recommended',
      category: 'AI SDK',
    },
    {
      name: 'deepseek-ai/deepseek-coder',
      summary: 'DeepSeek 推出的开源代码生成模型，在 CodeLlama 基准上表现优异',
      techStack: ['Python', 'PyTorch', 'Transformers'],
      features: [
        '代码生成能力强',
        '支持多种编程语言',
        '开源可商用',
        '本地部署友好',
      ],
      trendingReason: '开源代码大模型竞争激烈，DeepSeek 推出性能更好的开源模型',
      recommendationScore: 7,
      recommendationReason: '开源社区需要更多选择，本地部署场景实用',
      isNewProject: true,
      starsChange: 2345,
      popularityTrend: 'new',
      highlightLevel: 'recommended',
      category: 'AI 模型',
    },
    {
      name: 'langchain-ai/langchain',
      summary: 'LangChain 是构建 AI 应用的强大框架，支持多种大模型和工具链',
      techStack: ['TypeScript', 'Python'],
      features: [
        '链式调用',
        '记忆管理',
        '文档加载器',
        '向量数据库集成',
      ],
      trendingReason: 'LangChain 生态系统持续增长，社区活跃度很高',
      recommendationScore: 7,
      recommendationReason: '生态完善，组件丰富，适合复杂应用',
      isNewProject: false,
      starsChange: 432,
      popularityTrend: 'stable',
      highlightLevel: 'watch',
      category: 'AI 框架',
    },
    {
      name: 'microsoft/semantic-kernel',
      summary: '微软推出的 AI 应用开发框架，专注于将 AI 能力集成到应用中',
      techStack: ['C#', 'Python', 'TypeScript'],
      features: [
        '技能（Skills）系统',
        '插件集成',
        '企业级支持',
        '多语言绑定',
      ],
      trendingReason: '微软的 AI 战略持续推进，Semantic Kernel 成为重要工具',
      recommendationScore: 6,
      recommendationReason: '企业用户友好，微软生态集成紧密',
      isNewProject: false,
      starsChange: 234,
      popularityTrend: 'rising',
      highlightLevel: 'watch',
      category: 'AI 框架',
    },
    {
      name: 'huggingface/transformers',
      summary: 'Hugging Face 推出的最流行的深度学习框架 Transformer 实现',
      techStack: ['Python', 'PyTorch', 'JAX'],
      features: [
        '模型库丰富',
        '预训练模型',
        '简单易用',
        '社区支持强',
      ],
      trendingReason: 'Transformers 成为深度学习标准框架，持续添加新模型',
      recommendationScore: 8,
      recommendationReason: '事实标准，资源丰富，新手友好',
      isNewProject: false,
      starsChange: 789,
      popularityTrend: 'stable',
      highlightLevel: 'recommended',
      category: '深度学习',
    },
    {
      name: 'chroma-core/chroma',
      summary: '轻量级向量数据库，专注于 RAG（检索增强生成）场景',
      techStack: ['Rust', 'TypeScript', 'Python'],
      features: [
        '轻量易部署',
        '快速检索',
        '成本较低',
        'RAG 友好',
      ],
      trendingReason: 'RAG 应用增长带动向量数据库需求',
      recommendationScore: 6,
      recommendationReason: 'RAG 场景实用，部署成本低',
      isNewProject: true,
      starsChange: 1567,
      popularityTrend: 'new',
      highlightLevel: 'watch',
      category: '数据库',
    },
    {
      name: 'lancedb/lancedb',
      summary: 'LanceDB 是专为 AI 应用设计的向量数据库，支持大规模向量搜索',
      techStack: ['Rust', 'Python', 'Arrow'],
      features: [
        '高性能向量搜索',
        '大规模扩展',
        'Arrow 生态',
        'AI 原生',
      ],
      trendingReason: '向量数据库竞争激烈，LanceDB 凭借性能优势获得关注',
      recommendationScore: 6,
      recommendationReason: '性能优秀，适合大规模 AI 应用',
      isNewProject: true,
      starsChange: 890,
      popularityTrend: 'new',
      highlightLevel: 'watch',
      category: '数据库',
    },
    {
      name: 'meta-llama/llama3',
      summary: 'Meta 推出的 Llama 3 系列开源大模型，性能接近商业模型',
      techStack: ['Python', 'PyTorch'],
      features: [
        '性能优异',
        '开源可商用',
        '多尺寸模型',
        '推理效率高',
      ],
      trendingReason: '开源大模型持续突破，Llama 3 性能大幅提升',
      recommendationScore: 8,
      recommendationReason: '开源领导者，性能强劲，社区支持强',
      isNewProject: false,
      starsChange: 2100,
      popularityTrend: 'rising',
      highlightLevel: 'recommended',
      category: 'AI 模型',
    },
  ],
  summary: '今日 GitHub Trending 以 AI 相关项目为主导，特别是 AI Agent 开发工具、向量数据库和开源大模型成为热点。推荐重点关注 Anthropic 的 Claude Agent SDK，它提供了完整的 Agent 开发能力，适合构建复杂的 AI 应用。',
}

console.log('生成测试邮件...')
const emailHtml = generateEmail(mockAnalysis)
console.log('邮件生成完成!')
console.log('邮件长度:', emailHtml.length, '字符')

writeFileSync('./test-email.html', emailHtml)
console.log('测试邮件已保存到: ./test-email.html')
console.log('请在浏览器中打开查看效果')
